version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: tm-digital-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - tm-digital_network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tm-digital-backend
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - tm-digital_network

networks:
  tm-digital_network:
    driver: bridge

